language: cpp
compiler: clang
os:
  - linux
  - osx

addons:
  apt:
    packages:
    - cmake
    - libjpeg-turbo8-dev
before_install: ./travis-deps.sh
script: ./travis-build.sh
cache:
    apt: true
    ccache: true
    directories:
    - $HOME/deps
