language: cpp
os:
  - linux
  - osx

addons:
  apt:
    packages:
    - cmake
    - sdl2
    - libjpeg-turbo8-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2 jpeg-turbo; fi

